django-social/dwitter/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile, login_page, submit_login, view_logout, view_signup

app_name = "dwitter"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("login/", login_page, name="login_page"),
    path("login/submit", submit_login, name="submit_login"),
    path("logout/", view_logout, name="view_logout"),
    path("signup/", view_signup, name="view_signup"),
]

django-social/social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("dwitter.urls")),
    path('admin/', admin.site.urls),
]

django-social/dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username


class Dweet(models.Model):
    user = models.ForeignKey(
        User, related_name="dweets", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return(
            f'{self.user}'
            f'{self.created_at:%d-%m-%Y %H:%M}'
            f'{self.body[:30]}...'
        )


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        # user_profile.follows.set([instance.profile.id])
        user_profile.save()

# create a Profile for each new user
# post_save.connect(create_profile, sender=User)

django-social/dwitter/forms.py
from django import forms
from .models import Dweet

class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Escreva seu Dweet...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
        error_messages={'max_length':'Este dweet está muito longo! Observe o limite de 140 caracteres.'}
    )

    class Meta:
        model = Dweet
        exclude = ("user", )

django-social/dwitter/views.py
from django.shortcuts import render, redirect
from .models import Profile, Dweet
from .forms import DweetForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.

@login_required(login_url='/login/')
def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("dwitter:dashboard")
    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")
    return render(request, "dwitter/dashboard.html", {"form": form, "dweets":followed_dweets})

@login_required(login_url='/login/')
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles":profiles})

@login_required(login_url='/login/')
def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow" and current_user_profile != profile:
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "dwitter/profile.html", {"profile": profile})
    # return render(request, "dwitter/profile.html", {"profile": profile, "followers":get_followers(pk)})

def login_page(request):
    return render(request, "dwitter/login.html")

def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        usuario = authenticate(username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('/')
        else:
            messages.error(request, "Usuário ou senha inválidos")
    return redirect('/')

def view_logout(request):
    logout(request)
    return redirect('/login')

def view_signup(request):
    return render(request, "dwitter/signup.html")


# IMPLEMENTAR A OPÇÃO DE DELETAR DWEETS!

# solução alternativa para obter os seguidores,
# utilizada antes de verificar a possibilidade de se usar o atributo related_name no model Profile
# def get_followers(pk):
#     return Profile.objects.filter(follows=pk)

django-social/dwitter/templates/base.html
<!-- dwitter/templates/base.html -->

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Dwitter</title>
</head>
<body>

<a href="{% url 'dwitter:dashboard' %}">
  <section class="hero is-small is-success mb-4">
    <div class="hero-body">
        <h1 class="title is-1">Dwitter</h1>
        <p class="subtitle is-4">Sua pequena rede social, criada com Django</p>
    </div>
  </section>
</a>

<div class="container">
    <div class="columns">
        <div class="column is-1">
            {% if user.is_authenticated %}
                Olá, {{ user.username }}
                <a href="{% url 'dwitter:logout' %}">
                    <button class="button is-warning">
                        Sair
                    </button>
                </a>
            {% else %}
                Não tem cadastro?<br><a href="{% url 'dwitter:view_signup' %}">Registre-se!</a>
            {% endif %}
        </div>
        {% block content %}

        {% endblock content %}
    </div>
</div>

<footer class="footer">
  <div class="content has-text-centered">
      2022 . Desenvolvido por Eduardo Demuner
  </div>
</footer>
</body>
</html>

django-social/dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="column">
    {% for dweet in dweets %}
        <div class="box">
            {{dweet.body}}
            <span class="is-small has-text-grey-light">
                {{ dweet.created_at }} por {{ dweet.user.username }}
            </span>
        </div>
    {% endfor %}
    </div>

    <div class="column">
        <div class="block">
            <a href="{% url 'dwitter:profile_list' %} ">
                <button class="button is-dark is-outlined is-fullwidth">
                    Todos os perfis
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
                <button class="button is-success is-light is-outlined is-fullwidth">
                    Meu perfil
                </button>
            </a>
        </div>
        <div class="block">
            <div class="block">
                <h2 class="title is-2">Fazer um Dweet</h2>
            </div>
            <div class="block">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="button is-success is-fullwidth is-medium mt-5"
                            type="submit">
                        Dweetar
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

django-social/dwitter/templates/dwitter/login.html
{% extends 'base.html' %}

{% block content %}
<br><br>




    <form action="submit" method="POST">{% csrf_token %}
         <div class="column is-two-thirds">
             <h1 class="title is-1">Login</h1>
            <br><br>
            <label class="title is-4">Usuário:</label>
            <input class="input is-primary" type="text" placeholder="E-mail cadastrado conosco" name="username">
            <br><br>
            <label class="title is-4">Senha:</label>
            <input class="input is-primary" type="password" placeholder="***********" name="password">
            <br><br>
            <button class="button is-primary" type="submit">Entrar</button>

        </div>
    </form>

{% endblock content %}

django-social/dwitter/templates/dwitter/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'base.html' %}

{% block content %}

<div class="columns">
    <div class="column">

        <div class="block">
            <h1 class="title is-1">
                Dweets de {{ profile.user.username|upper }}
            </h1>
            <form method="post">
                {% csrf_token %}
                <div class="buttons has-addons">
                    {% if profile in user.profile.follows.all %}
                        <button class="button is-success is-static">Seguir</button>
                        <button class="button is-danger"
                        name="follow" value="unfollow">Desseguir</button>
                    {% else %}
                        <button class="button is-success"
                        name="follow" value="follow">Seguir</button>
                        <button class="button is-danger is-static">Desseguir</button>
                    {% endif %}
                </div>
            </form>
        </div>

        <div class="content">

    {% for dweet in profile.user.dweets.all %}
        <div class="box">
            {{ dweet.body }}
            <span class="is-small has-text-grey-light">
                {{ dweet.created_at }}
            </span>
        </div>
    {% endfor %}
</div>

    </div>


    <div class="column is-one-third">

        <div class=block>
            <a href="{% url 'dwitter:profile_list' %}">
                <button class="button is-dark is-outlined is-fullwidth">
                    Todos os perfis
                </button>
            </a>
        </div>


        <div class="block">
            <h3 class="title is-4">
                Quem {{ profile.user.username }} segue:
            </h3>
            <div class="content">
                <ul>
                    {% for following in profile.follows.all %}
                        <li>
                            <a href="{% url 'dwitter:profile' following.id %}">
                                {{ following }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="block">
            <h3 class="title is-4">
                    Quem segue {{ profile.user.username }}:
            </h3>
            <div class="content">
                <ul>
                    {% for follower in profile.followed_by.all %}
                        <li>
                            <a href="{% url 'dwitter:profile' follower.id %}">
                                {{ follower }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>
</div>





{% endblock content %}

django-social/dwitter/templates/dwitter/profile_list.html
<!-- dwitter/templates/dwitter/profile_list.html -->

{% extends 'base.html' %}

{% block content %}

{% for profile in profiles %}

<div class=""block>
    <div class=""card>
        <a href="{% url 'dwitter:profile' profile.id %}">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">{{ profile.user.username }}</p>
                        <p class="subtitle is-6">@{{ profile.user.username|lower }}</p>
                    </div>
                </div>
            </div>
        </a>
    </div>

{% endfor %}

</div>

{% endblock content %}

django-social/dwitter/templates/dwitter/signup.html
{% extends 'base.html' %}

{% block content %}



{% endblock content %}